# Generated by Django 4.0.4 on 2022-05-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
