# Generated by Django 3.2.13 on 2022-05-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20220523_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('Gender', models.CharField(max_length=6, null=True)),
                ('Address', models.CharField(max_length=25, null=True)),
                ('Martual_status', models.CharField(max_length=50, null=True)),
                ('NumberOfAvailableVacationDays', models.CharField(max_length=10, null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('PhoneNumber', models.CharField(max_length=11, null=True)),
                ('Salary', models.CharField(max_length=10, null=True)),
                ('NumberOfActualApprovedVacationDays', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
