# Generated by Django 3.2.13 on 2022-05-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emp_id', models.IntegerField(default=0)),
            ],
        ),
    ]
